# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaU_l46-OxcoRkBc_mAkk6s2miqxr9vl
"""

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
sum = num1 + num2 + num3

print("The sum of the three numbers is:", sum)

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
if num1 > num2 and num1 > num3 :
  print ("num1 is greatest",num1)
elif num2 > num1 and num2 > num3 :
  print ("num2 is greatest",num2)
else :
  print("num3 is greatest",num3)

num1 = int(input("Enter the first number: ")) #enter value of any two integers
num2 = int(input("Enter the second number: "))
if num1 == num2: #checks if the numbers are equal
  print("Both numbers are equal")
if num1 > num2:#checks if the number is greater
  print (num1,"is greater",)
if num2 > num1: #checks if the number is greater
  print (num2,"is greater")
if num1 != num2:#checks if the numbers are equal or not
  print (num1," is not equal to ",num2)